version: "3.8"

services:
  api:
    build: ./api
    ports:
      - "3002:3002"
    volumes:
      - ./api:/app

    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo

  dashboard:
    build: ./dashboard
    ports:
      - "3000:3000" # Map container port 3000 to host port 3000
    volumes:
      - ./dashboard:/app

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
